default_install_hook_types:
  - pre-commit
  - pre-push
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      # Keep the order: linter, formatter, as linter fixes may require code reformatting.
      # Source: https://docs.astral.sh/ruff/integrations/#pre-commit
      - id: ruff
        stages:
          - manual
          - pre-commit
          - pre-push
      - id: ruff-format
        stages:
          - manual
          - pre-commit
          - pre-push
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        stages:
          - manual
          - pre-push
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python3 -m pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages:
          - manual
          - pre-push
