apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-deployment
  labels:
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: mtweeman/hajle-silesia_gui:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gui-service
spec:
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000