import pathlib
import tkinter

config = {'application_window': {'title': "Hajle Silesia Homebrewing System",
                                 'icon_path': pathlib.Path(__file__).parent / "./img/icon.png"
                                 },
          'tab_bar': {},
          'recipe': {'title': "Recipe",
                     },
          'user_settings': {'name': "user_settings",
                            'title': "User settings",
                            'row': 0,
                            'column': 0,
                            'columnspan': 3,
                            'sticky': tkinter.EW + tkinter.N,
                            },
          'miscs': {'name': "miscs",
                    'title': "Miscs",
                    'row': 1,
                    'column': 0,
                    'sticky': tkinter.NSEW,
                    },
          'fermentables': {'name': "fermentables",
                           'title': "Fermentables",
                           'row': 1,
                           'column': 1,
                           'sticky': tkinter.NSEW,
                           },
          'parameters': {'name': "parameters",
                         'title': "Parameters",
                         'row': 1,
                         'column': 2,
                         'rowspan': 2,
                         'sticky': tkinter.NSEW,
                         },
          'mash_steps': {'name': "mash_steps",
                         'title': "Mash steps",
                         'row': 2,
                         'column': 0,
                         'sticky': tkinter.NSEW,
                         },
          'hops': {'name': "hops",
                   'title': "Hops",
                   'row': 2,
                   'column': 1,
                   'sticky': tkinter.NSEW,
                   },
          'title': {'name': 'title',
                    'row': 0,
                    'column': 0,
                    'font': "TkHeadingFont",
                    'sticky': tkinter.NSEW,
                    },
          'records_and_parameters': {'row': 1,
                                     'column': 0,
                                     'sticky': tkinter.NSEW,
                                     },
          }
