name = "Hajle Silesia Homebrewing System"
packages = []
[[fetch]]
files = [
    "object_factory.py",
    "container.py",
    "./config/brewing_imgs_coords.csv",
    "./config/table_config.json",
    "menu.py",
    "recipe.py",
    "brewing.py",
    "pythonapi.py",
]
