packages = []
[files]
"./object_factory.py" = ""
"./container.py" = ""
"./listeners.py" = ""
"./config/brewing.csv" = "./config/brewing.csv"
"./config/ferm.csv" = "./config/ferm.csv"
"./config/menu.csv" = "./config/menu.csv"
"./config/recipe.csv" = "./config/recipe.csv"
"./config/table_config.json" = "./config/table_config.json"
"./menu.py" = ""
"./canvas.py" = ""
"./pythonapi.py" = ""
"./scripts/video-streaming.js" = "./scripts/video-streaming.js"
