packages = []
[files]
"./object_factory.py" = ""
"./container.py" = ""
"./events.py" = ""
"./config/brewing.csv" = "./config/brewing.csv"
"./config/fermentation.csv" = "./config/fermentation.csv"
"./config/table_config.json" = "./config/table_config.json"
"./menu.py" = ""
"./recipe.py" = ""
"./brewing.py" = ""
"./fermentation.py" = ""
"./pythonapi.py" = ""
"./scripts/video-streaming.js" = "./scripts/video-streaming.js"
