name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Tests and static analysis
    runs-on: ubuntu-latest
    container:
      image: hajlesilesia/provisioning:0.44.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit-zipapp
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Run tests and static analysis
        run: |
          pre-commit run --all-files --hook-stage manual

  image-build:
    needs:
      - test
    name: Image build
    uses: hajle-silesia/.github/.github/workflows/shared-image-build.yaml@v2.6.0
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}

  chart-update:
    needs:
      - image-build
    name: Chart update
    uses: hajle-silesia/.github/.github/workflows/shared-chart-update.yaml@v2.6.0
    with:
      docker-hub-image-repository-name: ${{ needs.image-build.outputs.docker-hub-repository-name }}
      image-tag: ${{ needs.image-build.outputs.tag }}
    secrets:
      github-token: ${{ secrets.PUSH_TOKEN }}
