name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests-and-static-analysis:
    name: Tests and static analysis
    uses: hajle-silesia/.github/.github/workflows/shared-tests-and-static-analysis.yaml@v2.6.1
    with:
      python-dependencies: true

  image-build:
    needs:
      - tests-and-static-analysis
    name: Image build
    uses: hajle-silesia/.github/.github/workflows/shared-image-build.yaml@v2.6.1
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}

  chart-update:
    needs:
      - image-build
    name: Chart update
    uses: hajle-silesia/.github/.github/workflows/shared-chart-update.yaml@v2.6.1
    with:
      docker-hub-image-repository-name: ${{ needs.image-build.outputs.docker-hub-repository-name }}
      image-tag: ${{ needs.image-build.outputs.tag }}
    secrets:
      github-token: ${{ secrets.PUSH_TOKEN }}
